# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: z3ntu
email: luca@z3ntu.xyz
#bitcoin_addr: 1z3ntuC4fYSLawSQu153kia9FuL4i2e4M
description: > # this means to ignore newlines until "baseurl:"
  This is my blog and website, where I write about different things and present my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://z3ntu.github.io" # the base hostname & protocol for your site
twitter_username: z3ntu
github_username:  z3ntu
youtube_username: z3ntu
youtube_url: channel/UCzTg_UdcLZiC90CMFBhTEQg

# Build settings
markdown: kramdown
exclude:
  - localhost.sh
  - deploy.sh
  - brainstorming/
