baseURL = "https://blog.z3ntu.xyz"
languageCode = "en-us"
title = "z3ntu"
theme = "paper"
copyright = "&copy; {year} Luca Weiss"

[params]
  mainSections = ["post"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Projects"
    pre = "<i class='fa fa-code fa-fw'></i>"
    weight = 2
    identifier = "projects"
    url = "/projects/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 4
    identifier = "about"
    url = "/about/"

[markup.goldmark.renderer]
  unsafe = true

[social]
  mastodon = "https://fosstodon.org/@z3ntu"
