baseURL = "https://lucaweiss.eu"
languageCode = "en-us"
title = "Luca Weiss"
theme = "paper"
copyright = "&copy; {year} Luca Weiss"

[params]
  mainSections = ["post"]
  [params.social]
    mastodon = "https://fosstodon.org/@z3ntu"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
    [menu.main.params]
      hideInGemini = true
  [[menu.main]]
    name = "Projects"
    pre = "<i class='fa fa-code fa-fw'></i>"
    weight = 2
    identifier = "projects"
    url = "/projects/"
  [[menu.main]]
    name = "Talks"
    pre = "<i class='fa fa-code fa-fw'></i>"
    weight = 3
    identifier = "talks"
    url = "/talks/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 4
    identifier = "post"
    url = "/post/"
    [menu.main.params]
      hideInGemini = true
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"

[markup.goldmark.renderer]
  unsafe = true

[mediaTypes."text/gemini"]
  suffixes = ["gmi"]

[outputFormats.gemini]
  name = "gemini"
  isPlainText = true
  isHTML = false
  mediaType = "text/gemini"
  protocol = "gemini://"
  permalinkable = true

[outputs]
  home = ["html", "rss", "gemini"]
  page = ["html", "gemini"]
