baseURL = "https://blog.z3ntu.xyz"
languageCode = "en-us"
title = "z3ntu"
theme = "blackburn"
copyright = "&copy; 2020 Luca Weiss"

[params]
  subtitle = "Luca Weiss"
  brand = "z3ntu"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Projects"
    pre = "<i class='fa fa-code fa-fw'></i>"
    weight = 2
    identifier = "projects"
    url = "/projects/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 4
    identifier = "about"
    url = "/about/"

[social]
  github = "z3ntu"
  gitlab = "z3ntu"
  twitter = "z3ntu"
  mastodon = "https://fosstodon.org/@z3ntu"
  linkedin = "luca-weiss"
  srht = "~z3ntu"
